name: Cheapest Flight Finder

on:
    schedule:
        # Runs every day at 08:00 UTC (adjust if needed)
        - cron: "0 8 * * *"
    workflow_dispatch: # lets you run it manually from GitHub

jobs:
    run-script:
        runs-on: ubuntu-latest
        permissions:
            contents: read # no write needed, avoids the 403 error
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run script
              env:
                  AMADEUS_CLIENT_ID: ${{ secrets.AMADEUS_CLIENT_ID }}
                  AMADEUS_CLIENT_SECRET: ${{ secrets.AMADEUS_CLIENT_SECRET }}
                  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
                  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
              run: |
                  python cheapest_flight_finder.py
